oven:
  groups:
    3_CO_PLC_A:
      conditions:
      - column: '[3_CO_PLC_A]IB       6'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 2.5
      confirmed: false
    3_CO_PLC_B:
      conditions:
      - column: '[3_CO_PLC_B]IB       6'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 2.5
      confirmed: false
    3_C_CAR_1:
      conditions:
      - column: '[3_C_CAR_1]IB       2'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 36.50000000000002
      confirmed: false
    3_C_CAR_2:
      conditions:
      - column: '[3_C_CAR_2]IB       9'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 55.0
      confirmed: false
    3_C_CAR_3:
      conditions:
      - column: '[3_C_CAR_3]IB      40'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 68.0
      confirmed: false
    3_ECS_PLC_A:
      conditions:
      - column: '[3_ECS_PLC_A]QB      19'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 4.9999999999999964
      confirmed: false
    3_ECS_PLC_B:
      conditions:
      - column: '[3_ECS_PLC_B]IB      10'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 213.99999999999997
      confirmed: false
    3_LOCO_A:
      conditions:
      - column: '[3_LOCO_A]MB       8'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 31.99999999999995
      confirmed: false
    3_LOCO_B:
      conditions:
      - column: '[3_LOCO_B]QB      17'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 2.9999999999999982
      confirmed: false
    3_P_CAR_1:
      conditions:
      - column: '[3_P_CAR_1]IB      64'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 29.999999999999993
      confirmed: false
    3_P_CAR_2:
      conditions:
      - column: '[3_P_CAR_2]IB      65'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 4.000000000000005
      confirmed: false
    4_CO_PLC_A:
      conditions:
      - column: '[4_CO_PLC_A]QB      13'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 139.0
      confirmed: false
    4_CO_PLC_B:
      conditions:
      - column: '[4_CO_PLC_B]QB      13'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 138.99999999999997
      confirmed: false
    4_ECS_PLC_A:
      conditions:
      - column: '[4_ECS_PLC_A]IB      15'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 20.999999999999964
      confirmed: false
    4_ECS_PLC_B:
      conditions:
      - column: '[4_ECS_PLC_B]IB      17'
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 191.0
      confirmed: false
    __default__:
      conditions:
      - column: DB421.DBW 4
        confidence: 1.0
        op: '>'
        source: bimodal
        value: 15.5
      confirmed: false
